spring.application.name=searchservice
server.port=9090
spring.datasource.url=jdbc:postgresql://localhost:5432/searchservice
spring.datasource.username=postgres
spring.datasource.password=123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
jwt.secret=dGhpcy1pcy1hLXRlc3Qta2V5LWZvci1qd3Qtc2lnbmluZw==
jwt.expiration=8,64,00,000